import * as fs from "node:fs";
import * as path from "node:path";
import { Enum, Namespace, NamespaceBase, Root, Type } from "protobufjs";

const PrefixPattern = /^(C2S|S2C|C2G|G2C)/;

export class LuaDescGenerator {
    private lines: string[] = [];
    private depth = 0;

    generate(root: Root, targetLuaPath: string) {
        this.lines = [];
        this.depth = 0;

        if (!fs.existsSync(targetLuaPath)) {
            console.error(`[Error] targetLuaPath not exists: ${targetLuaPath}`);
            process.exit(1);
        }

        this.push(`-- Auto generated by export-proto-to-kts.`);
        this.push(`---@class ProtoDescs`);
        this.stepIn(`local ProtoDescs = {`);
        this.parseNamespaceBase(root);
        this.stepOut("}\n");
        this.push("return ProtoDescs");

        fs.writeFileSync(path.join(targetLuaPath, "ProtoDescs.lua"), this.lines.join("\n"));
    }

    private parseNamespaceBase(obj: NamespaceBase, parentName?: string) {
        if (obj.nestedArray.length <= 0) return;
        if (!(obj instanceof Root)) this.stepIn(`${obj.name} = {`);
        const pName = parentName ? `${parentName}.${obj.name}` : obj.name;
        const sorted = [...obj.nestedArray].sort((a, b) => a.name.localeCompare(b.name));
        for (const child of sorted) {
            if (!child) continue;
            if (child instanceof Enum) this.parseEnum(child);
            else if (child instanceof Type) this.parseType(child, pName);
            else if (child instanceof Namespace) this.parseNamespaceBase(child, pName);
        }
        if (!(obj instanceof Root)) this.stepOut(`},`);
    }

    private parseEnum(obj: Enum) {
        this.stepIn(`${obj.name} = {`);
        for (const [key, val] of Object.entries(obj.values)) {
            this.push(`${key} = ${val},`);
        }
        this.stepOut(`},`);
    }

    private parseType(obj: Type, parentName?: string) {
        this.parseNamespaceBase(obj);
        if (PrefixPattern.test(obj.name)) {
            const fullName = parentName ? `${parentName}.${obj.name}` : obj.name;
            this.push(`${obj.name} = "${fullName}",`);
        }
    }

    private stepIn(msg: string) {
        this.push(msg);
        this.depth++;
    }

    private stepOut(msg: string) {
        if (this.depth <= 0) return;
        this.depth--;
        this.push(msg);
    }

    private push(str: string) {
        this.lines.push("\t".repeat(this.depth) + str);
    }
}
