import * as fs from "node:fs";
import * as path from "node:path";
import { Enum, Field, Namespace, NamespaceBase, Root, Type } from "protobufjs";

import {
    EProtocolType,
    PROTO_BOOLEAN_TYPE,
    PROTO_NUMBER64_TYPE,
    PROTO_NUMBER_TYPE,
    PROTO_STRING_TYPE,
    PROTO_UINT8ARRAY_TYPE,
    PROTOCOL_REGISTER_FUNC_MAP,
    TYPE_PREFIX_ENUM,
    TYPE_PREFIX_INTERFACE,
} from "./Define";

// protobufjs 未导出 Field.keyType，用声明扩展
declare module "protobufjs" {
    interface Type {
        params: Map<string, string | string[]>;
    }
    interface Field {
        keyType: string;
    }
}

// ============================================================
// 工具函数
// ============================================================

function generatePath(obj: Namespace | null): string[] {
    if (obj === null || obj instanceof Root) return [];
    return [...generatePath(obj.parent), obj.name];
}

function qualifiedTypeName(obj: NamespaceBase, isRaw = false): string {
    const parts = generatePath(obj.parent);
    const prefix = isRaw ? "" : obj instanceof Enum ? TYPE_PREFIX_ENUM : TYPE_PREFIX_INTERFACE;
    return `${parts.join(".")}.${prefix}${obj.name}`;
}

function getProtocolType(obj: Type): EProtocolType | undefined {
    for (const [type] of PROTOCOL_REGISTER_FUNC_MAP) {
        const prefix = EProtocolType[type];
        if (obj.name.startsWith(prefix)) return type as unknown as EProtocolType;
    }
    return undefined;
}

function parseTypeMetadata(obj: Type): Map<string, string | string[]> {
    const params = new Map<string, string | string[]>();
    obj.comment
        ?.split(/[\r\n]+/)
        .map((line) => {
            const idx = line.indexOf(" ");
            return idx === -1 ? [line, ""] : [line.slice(0, idx), line.slice(idx + 1)];
        })
        .forEach(([key, value]) => {
            const old = params.get(key);
            if (old) {
                if (Array.isArray(old)) old.push(value);
                else params.set(key, [old, value]);
            } else {
                params.set(key, value);
            }
        });
    return params;
}

// ============================================================
// TsIndexGenerator
// ============================================================

export class TsIndexGenerator {
    private lines: string[] = [];
    private depth = 0;
    private protocolMap = new Map<EProtocolType, Type[]>();
    private number64TargetType?: string;
    private convertPBMapToJSMap: boolean;
    /** 协议注册函数(registerC2SProtocol/registerS2CProtocol)所在模块;未配置时不生成注册代码 */
    private protocolRegisterModule?: string;

    constructor(opts: { number64TargetType?: string; convertPBMapToJSMap?: boolean; protocolRegisterModule?: string }) {
        this.number64TargetType = opts.number64TargetType;
        this.convertPBMapToJSMap = opts.convertPBMapToJSMap ?? (opts.number64TargetType != null);
        this.protocolRegisterModule = opts.protocolRegisterModule;
        for (const key of PROTOCOL_REGISTER_FUNC_MAP.keys()) {
            this.protocolMap.set(key, []);
        }
    }

    generate(root: Root, targetTsPath: string) {
        this.lines = [];
        this.depth = 0;

        const dir = path.join(targetTsPath, ...generatePath(root));
        fs.mkdirSync(dir, { recursive: true });

        const filename = path.join(dir, "index.ts");

        this.push(`/**`);
        this.push(` * Auto generated by export-proto-to-kts.`);
        this.push(` */\n`);
        this.push(`/* eslint-disable @typescript-eslint/no-namespace */`);
        this.push(`/* eslint-disable @typescript-eslint/no-empty-interface */\n`);
        this.push(`import { F } from "k-ts-framework";`);
        if (this.protocolRegisterModule) {
            this.push(
                `import { registerC2SProtocol, registerS2CProtocol } from "${this.protocolRegisterModule}";\n`,
            );
        }
        this.push(`export * as $root from "./pb-bundle";\n`);

        this.parseNamespaceBase(root);
        this.parseNamespaceAction("go");
        this.parseNamespaceAction("py");

        if (this.protocolRegisterModule) {
            this.protocolMap.forEach((protocols, type) => {
                protocols.forEach((protocol) => this.parseProtocolRegister(type, protocol));
            });
        }

        fs.writeFileSync(filename, this.lines.join("\n"));
    }

    // ---- 递归遍历 ----

    private parseNamespaceBase(obj: NamespaceBase) {
        if (obj.nestedArray.length <= 0) return;
        if (!(obj instanceof Root)) this.stepIn(`export namespace ${obj.name} {`);
        const sorted = [...obj.nestedArray].sort((a, b) => a.name.localeCompare(b.name));
        for (const v of sorted) {
            if (!v) continue;
            if (v instanceof Enum) this.parseEnum(v);
            else if (v instanceof Type) this.parseType(v);
            else if (v instanceof Namespace) this.parseNamespaceBase(v);
        }
        this.stepOut(`}\n`);
    }

    private parseNamespaceAction(server: string) {
        this.stepIn(`export namespace ${server} {`);
        this.protocolMap.forEach((protocols, type) => {
            protocols
                .filter((p) => p.params.get("@server") === server)
                .forEach((p) => this.parseProtocol(type, p));
        });
        this.stepOut(`}\n`);
    }

    private parseEnum(obj: Enum) {
        this.stepIn(`export enum ${TYPE_PREFIX_ENUM}${obj.name} {`);
        Object.entries(obj.values).forEach(([key, val]) => {
            this.push(`${key} = ${val},`);
        });
        this.stepOut(`}\n`);
    }

    private parseType(obj: Type) {
        const metadata = parseTypeMetadata(obj);
        this.parseNamespaceBase(obj);

        this.stepIn(`export interface ${TYPE_PREFIX_INTERFACE}${obj.name} {`);

        // oneof 字段（排除 proto3 可选字段的伪 oneof）
        obj.oneofsArray.forEach((oneof) => {
            if (oneof.name.startsWith("_") && obj.fields[oneof.name.substring(1)]) return;
            this.push(`${oneof.name}: ${oneof.fieldsArray.map((f) => `"${f.name}"`).join(" | ")},`);
        });

        const nullable = metadata.get("@nullable");
        const nullableList = nullable ? (Array.isArray(nullable) ? nullable : [nullable]) : undefined;

        Object.values(obj.fields).forEach((field) => {
            this.parseField(field, nullableList?.includes(field.name));
        });

        if (metadata.has("@inject")) {
            const inject = metadata.get("@inject")!;
            Array.isArray(inject) ? inject.forEach((l) => this.push(l)) : this.push(inject);
        }
        this.stepOut(`}\n`);

        const protocolType = getProtocolType(obj);
        if (protocolType !== undefined) {
            obj.params = metadata;
            obj.params.has("@server") || obj.params.set("@server", "go");
            obj.params.has("@cmd") || obj.params.set("@cmd", qualifiedTypeName(obj, true));
            this.protocolMap.get(protocolType)?.push(obj);
        }
    }

    private parseField(field: Field, nullable?: boolean) {
        const typeName = this.fieldTypeName(field);
        const undefinable = field.partOf || nullable;
        this.push(`${field.name}${undefinable ? "?: " : ": "}${typeName}${nullable ? " | null" : ""},`);
    }

    private parseProtocol(protocolType: EProtocolType, obj: Type) {
        const isS2C = protocolType === EProtocolType.S2C;
        const server = obj.params.get("@server");
        this.stepIn(`export class ${obj.name} extends F.Action {`);
        this.stepIn(
            `public constructor(public data: ${qualifiedTypeName(obj)}${
                isS2C ? `, public code: ${server === "py" ? "number | string" : "zero.game.ECode"}` : ""
            }) {`,
        );
        this.push(`super();`);
        this.stepOut(`}`);
        this.stepOut(`}\n`);
    }

    private parseProtocolRegister(protocolType: EProtocolType, obj: Type) {
        const registerFuncName = PROTOCOL_REGISTER_FUNC_MAP.get(protocolType)!;
        const action = `${obj.params.get("@server")}.${obj.name}`;
        const meta = obj.params.get("@meta");
        this.push(
            `${registerFuncName}("${obj.params.get("@cmd")}", "${qualifiedTypeName(obj, true)}", ${action}${
                meta ? `, "${meta}")` : ")"
            };`,
        );
    }

    // ---- 字段类型名 ----

    private fieldTypeName(field: Field): string {
        const base = this.fieldBaseTypeName(field);
        if (field.repeated) return `${base}[]`;
        if (field.map) {
            if (this.convertPBMapToJSMap) {
                return `Map<${this.convertBasicTypeName(field.keyType) ?? "string"}, ${base}>`;
            }
            return `{ [key: ${field.keyType === "string" ? "string" : "number"}]: ${base} }`;
        }
        return base;
    }

    private fieldBaseTypeName(field: Field): string {
        const basic = this.convertBasicTypeName(field.type);
        if (basic) return basic;

        const resolved = field.parent?.lookupTypeOrEnum(field.type);
        if (resolved) return qualifiedTypeName(resolved);
        return "unknown";
    }

    private convertBasicTypeName(type: string): string | undefined {
        if (PROTO_NUMBER_TYPE.includes(type)) return "number";
        if (PROTO_STRING_TYPE.includes(type)) return "string";
        if (PROTO_UINT8ARRAY_TYPE.includes(type)) return "Uint8Array";
        if (PROTO_BOOLEAN_TYPE.includes(type)) return "boolean";
        if (PROTO_NUMBER64_TYPE.includes(type)) return this.number64TargetType ?? "number";
        return undefined;
    }

    // ---- 输出控制 ----

    private stepIn(msg: string) {
        this.push(msg);
        this.depth++;
    }

    private stepOut(msg?: string) {
        if (this.depth <= 0) return;
        this.depth--;
        if (msg !== undefined) this.push(msg);
    }

    private push(str: string) {
        this.lines.push("\t".repeat(this.depth) + str);
    }
}
