/***************************************************************
 * Auto generated by exported-pipeline
 **************************************************************/

import { tempDataTable } from "game-data-collection";

export interface IUITemplate {
    id: number;
    name: string;
    resPath: string;
    storeTags: string[];
    testMap: Map<string, number>;
}

let dataTable = tempDataTable<IUITemplate>("client/ui", "id");

export function getAllTemplates(): Map<number, IUITemplate> | undefined {
    return dataTable();
}

export function getTemplate(id: number): IUITemplate | undefined {
    return getAllTemplates()?.get(id);
}

export function getTemplatesCount(): number | undefined {
    return getAllTemplates()?.size;
}

// [EXPORT_BEGIN]
export function getTemplateName(id: number) {
    let template = getTemplate(id);
    return template?.name;
}
// [EXPORT_END]
