import * as fs from "fs";
import * as path from "path";

import { DataWithSchema, getGlobalConfig, TaggedInfoExtraData } from "../../data";
import { ArrayFieldDeclaration, EFieldType, MapFieldDeclaration, OneOfDeclaration } from "../../field";
import { CustomFieldTextExporterHelper } from "../../misc/CustomFieldExporter";
import { ExportLogger } from "../../misc/ExportLogger";
import { ExportRunStats } from "../../misc/ExportRunStats";
import { assertWithLoc, formatLoc } from "../../misc/Localization";
import { TargetMapping } from "../../misc/TargetMapping";
import { assert, ensureDir, loadTextFileData, pathExists, writeFile } from "../../misc/Util";
import { Processor } from "../Base";
import { getSchemaTargetMappingSource, removeFileAndVerifyDir } from "../Util";

import type { Constructor, Schema } from "../../data";
import type { Field, FieldDeclaration, TemplateDeclarationSet } from "../../field";
import type { ITargetMappingConfig } from "../../misc/TargetMapping";
import type { IProcessorConfig } from "../Base";
// prettier-ignore
export const GENERATED_TS_FILE_HEADER = `/***************************************************************
 * Auto generated by export-flow
 **************************************************************/
`;

export const EOF = "\n";
export const TARGET_MAPPING_TYPE = "GenerateWithBaseName";

export interface IConfig extends IProcessorConfig {
    jsonTargetMapping: ITargetMappingConfig;
    targetDir: string;
    supportOldFeatures?: boolean;
    exportIterateFunc?: boolean;
    exportTemplateCountToTS?: boolean;
    outputLog?: boolean;
    importPathMap?: Record<string, string>;
}

/**
 * 重写生成 TS 代码里的 import 说明符。
 * importPathMap 缺省时原样返回,保证输出与未配置时逐字节一致。
 */
export function rewriteImportSpecifiers(lines: Array<string>, importPathMap?: Record<string, string>): Array<string> {
    if (!importPathMap) return lines;
    return lines.map((line) =>
        line.replace(/from "([^"]+)"/g, (matched: string, specifier: string) => {
            let mapped = importPathMap[specifier];
            return mapped ? `from "${mapped}"` : matched;
        }),
    );
}

interface ISchemaConfig {
    exportToTS?: boolean;
}

export class ExportInfoToTypeScript extends Processor<ExportInfoToTypeScript> {
    public inputDataType = DataWithSchema;
    public outputDataType = DataWithSchema;

    protected fileInDir?: Map<string, Array<string>>;
    protected scriptTargetMapping?: TargetMapping;
    protected jsonTargetMapping?: TargetMapping;
    protected schemaType?: Constructor<Schema>;
    protected customFieldHelper?: CustomFieldTextExporterHelper;

    public async processSingle(data: DataWithSchema) {
        if (this.schemaType && !(data.schema instanceof this.schemaType)) return data;

        let schema = data.schema;
        let schemaConfig = schema.config as ISchemaConfig;
        if (schemaConfig.exportToTS === false) return data;

        let jsonPath = await this.jsonTargetMapping!.getTarget(getSchemaTargetMappingSource(data.schema));
        if (!jsonPath) return data;

        let name = schema.config.name;
        let scriptPath = await this.scriptTargetMapping!.getTarget(name);
        if (!scriptPath) return data;

        jsonPath = jsonPath.replace(/\\/g, "/");

        let config = this.getConfig<IConfig>();
        if (config.outputLog) ExportLogger.logVerbose(formatLoc(`export-to-ts`, { scriptPath: scriptPath }));

        // if (await pathExists(scriptPath)) await rmPath(scriptPath);
        let dir = path.dirname(scriptPath);
        await ensureDir(dir);

        // 开始导出
        this.customFieldHelper = new CustomFieldTextExporterHelper(this);
        let out = new Array<string>();
        this.exportTS(data, name, jsonPath, out);
        out = rewriteImportSpecifiers(out, config.importPathMap);

        // 处理extra data
        let extraData = data.getExtraData(TaggedInfoExtraData);
        if (extraData && extraData.infos.length > 0) {
            out.push(getGlobalConfig().defaultExportInfoBeginKey);
            out.push(``);
            out = out.concat(...extraData.infos);
            out.push(getGlobalConfig().defaultExportInfoEndKey);
        }

        // 写文件
        this.customFieldHelper.onPreWriteFile(scriptPath, out);
        let fileContent = out.join(EOF);
        this.recordFileChange(scriptPath, fileContent);
        await removeFileAndVerifyDir(scriptPath);
        await writeFile(scriptPath, fileContent);

        // 记录导出的表
        let files = this.fileInDir!.get(dir);
        if (!files) {
            files = new Array<string>();
            this.fileInDir!.set(dir, files);
        }
        files.push(name);

        return data;
    }

    public async onPreProcessAll(allData: DataWithSchema[]) {
        this.fileInDir = new Map();
        let config = this.getConfig<IConfig>();
        this.scriptTargetMapping = await TargetMapping.create({
            type: TARGET_MAPPING_TYPE,
            targetDir: config.targetDir,
            extension: ".ts",
        });
        assertWithLoc(this.scriptTargetMapping, "invalid-target-mapping", {
            type: TARGET_MAPPING_TYPE,
            location: "ExportJsonDataTableToTypeScript",
        });

        this.jsonTargetMapping = await TargetMapping.create(config.jsonTargetMapping);
        assertWithLoc(this.jsonTargetMapping, "invalid-target-mapping", {
            type: config.jsonTargetMapping.type,
            location: "ExportJsonDataTableToTypeScript jsonPathTargetMapping",
        });
        return allData;
    }

    public async onPostProcessAll(allData: DataWithSchema[]) {
        // 导出index
        await this.exportIndex(allData);
        let exportedFileCount = 0;
        for (let files of this.fileInDir!.values()) exportedFileCount += files.length;
        if (this.getConfig<IConfig>().outputLog) ExportLogger.logKey(`ExportInfoToTypeScript summary: exported ${exportedFileCount} files`);
        return allData;
    }

    protected validateExportName(name: string) {
        return name.replaceAll("~", "_");
    }

    protected async exportIndex(allData: DataWithSchema[]) {
        let config = this.getConfig<IConfig>();
        let targetDir = path.resolve(config.targetDir);
        let existingFiles = await this.collectExistingTypeScriptFiles(targetDir);
        if (existingFiles.length > 0) {
            let files = this.fileInDir!.get(targetDir);
            if (!files) {
                files = new Array<string>();
                this.fileInDir!.set(targetDir, files);
            }
            files.push(...existingFiles);
        }

        let allFileDirs = Array.from(this.fileInDir!.entries()).map(([dir, files]) => [dir, Array.from(new Set(files))] as [string, string[]]);
        allFileDirs.sort((a, b) => a[0].localeCompare(b[0]));
        for (let [_, files] of allFileDirs) files.sort((a: string, b: string) => a.localeCompare(b));

        for (let [dir, files] of allFileDirs) {
            let indexFile = path.join(dir, "index.ts");

            // 新建与更新走同一个生成器:手工行(新建时为自动生成头)去尾部空行 → 一个空行 → 自动行 → 收尾换行。
            // 两个分支各写一份会产出不同字节,全量/增量来回切就制造无意义 diff。
            let existingContent = (await pathExists(indexFile)) ? await loadTextFileData(indexFile) : undefined;
            let manualLines = existingContent === undefined ? GENERATED_TS_FILE_HEADER.split(/\r?\n/) : this.stripGeneratedIndexLines(existingContent);
            let newContent = this.buildIndexContent(manualLines, files);
            if (newContent === existingContent) continue; // 无变化不写盘,保持增量幂等

            this.recordFileChange(indexFile, newContent);
            await writeFile(indexFile, newContent);
        }
    }

    /** 丢弃索引文件里的全部自动行,保留手工添加的其他行 */
    protected stripGeneratedIndexLines(content: string) {
        // 匹配历史两种自动行:`export * as X from "./F";`(Creator 3.8 预览 bundler 会静默丢弃该语法,
        // 运行时为 undefined,已废弃)与 `import * as X from "./F";`(现行格式,配套行 `export { X };`)
        const MATCH_REG = /^(?:export \* as|import \* as) (\w+) from "\.\/(.+)";/;
        const PAIR_EXPORT_REG = /^export \{ \w+ \};$/;

        let lines = content.split(/\r?\n/);
        let kept = new Array<string>();
        for (let i = 0; i < lines.length; ++i) {
            let line = lines[i];
            if (MATCH_REG.test(line)) {
                // 现行格式有配套 export 行,一并丢弃;旧格式无配套行
                if (line.includes("import * as") && i + 1 < lines.length && PAIR_EXPORT_REG.test(lines[i + 1])) ++i;
                continue;
            }
            kept.push(line);
        }
        return kept;
    }

    /** 索引文件唯一的字节形态:手工行 + 一个空行 + 按序自动行 + 收尾换行 */
    protected buildIndexContent(manualLines: Array<string>, files: Array<string>) {
        let lines = manualLines.slice();
        while (lines.length > 0 && lines[lines.length - 1].trim() === "") lines.pop();
        lines.push(``);

        for (let file of files) {
            let name = this.validateExportName(file);
            lines.push(`import * as ${name} from "./${file}";`);
            lines.push(`export { ${name} };`);
        }

        return lines.join(EOF) + EOF;
    }

    private async collectExistingTypeScriptFiles(dir: string) {
        if (!await pathExists(dir)) return [];

        let entries = await fs.promises.readdir(dir, { withFileTypes: true });
        return entries
            .filter((v) => v.isFile() && path.extname(v.name) === ".ts" && v.name !== "index.ts")
            .map((v) => path.basename(v.name, ".ts"));
    }

    private recordFileChange(targetPath: string, content: string) {
        if (!fs.existsSync(targetPath)) {
            ExportRunStats.getInstance().recordAdded(targetPath);
            return;
        }

        if (fs.readFileSync(targetPath, "utf-8") !== content) ExportRunStats.getInstance().recordModified(targetPath);
    }

    protected exportTS(data: DataWithSchema, tableName: string, jsonPath: string, out: Array<string>) {
        // 需要子类实现
    }

    protected exportInterface(name: string, declarationSet: TemplateDeclarationSet, baseClass: string, out: string[]) {
        let interfaceNames = new Map<string, string>();
        if (declarationSet.interfaces.size > 0) {
            let interfaceName;
            for (let [iName, iDecl] of declarationSet.interfaces) {
                interfaceName = `I${iName}`;
                interfaceNames.set(iName, interfaceName);
            }

            for (let [iName, iDecl] of declarationSet.interfaces) {
                interfaceName = interfaceNames.get(iName)!;

                let oneOfKey;
                let oneOfDeclString;
                if (iDecl instanceof OneOfDeclaration) {
                    let keyTypeField = iDecl.fields.get(iDecl.keyName);
                    assert(keyTypeField, `OneOfDeclaration keyName ${iDecl.keyName} is not found in fields.`);
                    oneOfKey = iDecl.keyName;

                    let value = "";
                    let index = 0;
                    iDecl.fields.forEach((fDecl, fName) => {
                        ++index;
                        if (fDecl === keyTypeField) return;
                        value += `"${fName}"` + (index < iDecl.fields.size ? "|" : ";");
                    });

                    oneOfDeclString = `${interfaceName.substring(1)}OneOfType`;
                    out.push(`export type ${oneOfDeclString} = ${value}`);
                }

                out.push(`export interface ${interfaceName} {`);
                for (let [fName, fDecl] of iDecl.fields) {
                    if (fName === oneOfKey) out.push(`\t${fName}${fDecl.optional === true ? "?" : ""}: ${oneOfDeclString};`);
                    else out.push(`\t${fName}${fDecl.optional === true ? "?" : ""}: ${this.buildSingleType(fDecl, interfaceNames)};`);
                }
                out.push(`}`);
                out.push(``);
            }
        }

        let templateName = `I${name}Template`;
        if (declarationSet.fields.size > 0) {
            out.push(`export interface ${templateName} extends ${baseClass} {`);
            for (let [fName, fDecl] of declarationSet.fields) {
                out.push(`\t${fName}${fDecl.optional === true ? "?" : ""}: ${this.buildSingleType(fDecl, interfaceNames)};`);
            }
            out.push(`}`);
            out.push(``);
        }

        return templateName;
    }

    protected buildSingleType(decl: FieldDeclaration, interfaceNames: Map<string, string>): string {
        if (decl instanceof ArrayFieldDeclaration) {
            let inner = decl.inner;
            let innerName = "";
            if (Array.isArray(inner)) {
                if (inner.length === 0) throw new Error(`ArrayFieldDeclaration inner is empty.`);
                for (let i = 0; i < inner.length; i++) {
                    innerName += this.buildSingleType(inner[i], interfaceNames);
                    if (i !== inner.length - 1) innerName += " | ";
                }
            } else {
                innerName = this.buildSingleType(inner, interfaceNames);
            }
            return `Array<${innerName}>`;
        } else if (decl instanceof MapFieldDeclaration) {
            let key = this.buildSingleType(decl.innerKey, interfaceNames);
            let value = this.buildSingleType(decl.innerValue, interfaceNames);
            return `Map<${key}, ${value}>`;
        } else {
            let name = interfaceNames.get(decl.type);
            if (name) return name;
            else return this.getFieldExportType(decl);
        }
    }

    protected getFieldExportName(field: Field): string {
        return field.config.alias ?? field.config.name;
    }

    protected getFieldExportType(decl: string | { type: string }): string {
        let type = typeof decl === "string" ? decl : decl.type;
        switch (type) {
            case EFieldType.Int:
            case EFieldType.UInt:
            case EFieldType.Float:
                return "number";
            case EFieldType.BigInt:
                return "bigint";
            // case EFieldType.UEResource:
            case EFieldType.String:
                return "string";
            case EFieldType.Bool:
                return "boolean";
            // case EFieldType.L10N:
            //     return "FText";
            case EFieldType.DataTableKey:
                assert(typeof decl !== "string", `getFieldExportType failed, DataTableKey is invalid`);
                return this.getFieldExportType((decl as any).keyType) as string;
            case EFieldType.OneOf:
                assert(typeof decl !== "string", `getFieldExportType failed, DataTableKey is invalid`);
                let customType2 = this.customFieldHelper!.verifyExportType(type);
                // assert(false, `invalid type ${type}`);
                return customType2 ?? type;
            default:
                let customType = this.customFieldHelper!.verifyExportType(type);
                // assert(false, `invalid type ${type}`);
                return customType ?? type;
        }
    }

    protected exportFunctionDeprecatedDesc(out: Array<string>, oldName: string, newName: string) {
        out.push("/**");
        out.push(` * @deprecated ${formatLoc(`deprecated-function`, { oldName: oldName, newName: newName })}`);
        out.push(" */");
    }
}
