import detectIndent from 'detect-indent';
import fs from 'node:fs';
import path from 'node:path';
import YAML from 'yaml';

import type { ILocalizationPaths } from '../Define.js';

// prettier-ignore
const LANGUAGE_EXPORT_YAML =
`# Generated by localization-tool, do not edit manually
name: DT{language}
key: id
keyNameLine: 4
dataStartLine: 5
multiSource: true
fields:
  - name: id
    type: string
  - name: translate
    type: string
  - name: generate_enum
    type: bool
    default: false
`;

interface IDeflateConfigSetting {
    configs: {
        name: string;
        tableName: string;
        matchPattern: string;
        inputFile: string;
        maxCountPerFile: number;
        keyType: string;
    }[];
}

async function createLanguageYaml(paths: ILocalizationPaths, lang: string) {
    const filePath = path.join(paths.translationConfigDir, `${lang}.yml`);
    if (fs.existsSync(filePath)) {
        console.log(`Language ${lang} already exists in settings, skipping creation.`);
        return;
    }
    const yaml = LANGUAGE_EXPORT_YAML.replace(/{language}/g, lang);
    await fs.promises.writeFile(filePath, yaml, "utf-8");
    console.log(`Created language exported YAML: ${filePath}`);
}

async function modifyDeflateConfigSetting(paths: ILocalizationPaths, lang: string) {
    const filePath = path.resolve(paths.translationConfigDir, "../../../deflate-config-setting.yml");
    const content = await fs.promises.readFile(filePath, "utf-8");
    const config = YAML.parse(content) as IDeflateConfigSetting;
    if (config.configs.find((data) => data.name === lang)) {
        console.log(`Language ${lang} already exists in deflate-config-setting.yml, skipping addition.`);
        return;
    }
    // 为了避免格式化问题，改为手动插入
    const indent = detectIndent(content).indent || "  ";
    const lines = content.split(/\r?\n/);
    const insertIndex = lines.findIndex((line) => line.trim() === "configs:") + 1;
    const newLines = [
        `${indent}- name: ${lang}`,
        `${indent}  tableName: DT${lang}`,
        `${indent}  matchPattern: \\/${lang}\\/${lang}.+\\.csv`,
        `${indent}  inputFile: /${lang}`,
        `${indent}  maxCountPerFile: 100`,
        `${indent}  keyType: string`,
        `${indent}  allowOverride: true`,
        `${indent}  packageName: ${lang}`,
    ];
    lines.splice(insertIndex, 0, ...newLines);
    const newContent = lines.join("\n");
    await fs.promises.writeFile(filePath, newContent, "utf-8");

    console.log(`Added language ${lang} to deflate-config-setting.yml`);
}

export async function genConfig(paths: ILocalizationPaths, validLangs: string[]) {
    console.log(`start generate config for all valid language.`);
    for (const lang of validLangs) {
        await createLanguageYaml(paths, lang);
        await modifyDeflateConfigSetting(paths, lang);

    }
    console.log(`[OK] Config generated successfully.`);
}
